inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3.0
  Include:
    - 'lib/**/*'
  Exclude:
    - 'examples/**/*'
    - 'samples/**/*'
    - 'tmp/**/*'
    - 'Rakefile'
    - '*.gemspec'
    - 'Gemfile'
  DisplayCopNames: true

# My personal style
# -----------------

Style/MultilineBlockChain:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/SignalException:
  EnforcedStyle: semantic

Style/RescueModifier:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Metrics/ParameterLists:
  CountKeywordArgs: false

# Experimenting with "what'll look more natural"
Style/LambdaCall:
  Enabled: false

# see http://zverok.github.io/blog/2016-02-23-control-flow.html
Style/AndOr:
  Enabled: false

# My style can't be described by any existing setting :(
Style/BlockDelimiters:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: "{}"

Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - '\#.*' # ignore long comments

# That's just how things are here
# -------------------------------

Metrics/MethodLength:
  Max: 15

Lint/NonLocalExitFromIterator:
  Enabled: false

# Those are just useless
# ----------------------

Style/EmptyCaseCondition:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false