inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3.0
  Include:
    - 'lib/**/*'
  Exclude:
    - 'examples/**/*'
    - 'samples/**/*'
    - 'tmp/**/*'
    - 'Rakefile'
    - '*.gemspec'
    - 'Gemfile'
  DisplayCopNames: true

# Ruby 2.3+
FrozenStringLiteralComment:
  Enabled: false

# My personal style
# -----------------

Style/MultilineBlockChain:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/SignalException:
  EnforcedStyle: semantic

Style/RescueModifier:
  Enabled: false

# see http://zverok.github.io/blog/2016-02-23-control-flow.html
Style/AndOr:
  Enabled: false

# My style can't be described by any existing setting :(
Style/BlockDelimiters:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: "{}"

# That's just how things are here
# -------------------------------

Metrics/AbcSize:
  Max: 18

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Max: 15

Lint/NonLocalExitFromIterator:
  Enabled: false

# Rubocop doesn't allow to "exclude comments" here, and good examples in
# comments require really long lines.
Metrics/LineLength:
  Enabled: false

# Working on it!
# --------------

Style/Documentation:
  Enabled: false

Style/Lambda:
  Exclude:
    - 'lib/tlaw/response_processor.rb'

# Those are just useless
# ----------------------

Style/EmptyCaseCondition:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# Broken cops
# -----------

# As of 0.52.1, it suggest to remove empty line inside _multiline string argument_.
# See https://github.com/bbatsov/rubocop/issues/5339
Layout/EmptyLinesAroundArguments:
  Enabled: false
